# Generated by Django 2.0.13 on 2019-10-22 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0037_commentsection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsection',
            old_name='user',
            new_name='author',
        ),
    ]
