# Generated by Django 2.0.13 on 2019-10-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0038_auto_20191022_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
