# Generated by Django 2.0.13 on 2019-10-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0039_board_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('added list', 'Add List'), ('edited list', 'Edit List'), ('added card', 'Add Card'), ('edited card', 'Edit Card'), ('archived card', 'Archive Card'), ('moved card', 'Moved Card'), ('attached a file to card', 'Add Attatchment'), ('removed an attatchment', 'Remove Attatchment')], max_length=1),
        ),
    ]
