# Generated by Django 2.0.13 on 2019-10-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0041_auto_20191022_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('added list', 'Add List'), ('edited list', 'Edit List'), ('added card', 'Add Card'), ('edited card', 'Edit Card'), ('archived card', 'Archive Card'), ('moved card', 'Moved Card'), ('attached file ', 'Add Attatchment'), ('removed attatchment', 'Remove Attatchment'), ('added checklist', 'Add Checklist'), ('removed checklist', 'Delete Checklist')], max_length=1),
        ),
    ]
