# Generated by Django 2.0.13 on 2019-10-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0043_auto_20191022_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcard',
            name='card_member',
            field=models.ManyToManyField(to='trello.BoardMembers'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('added list', 'Add List'), ('edited list', 'Edit List'), ('added card', 'Add Card'), ('edited card', 'Edit Card'), ('archived card', 'Archive Card'), ('moved card', 'Moved Card'), ('attached file on card', 'Add Attatchment'), ('removed attatchment on card', 'Remove Attatchment'), ('added checklist on card', 'Add Checklist'), ('removed checklist on card', 'Delete Checklist'), ('commented on card', 'Add Comment')], max_length=1),
        ),
    ]
