# Generated by Django 2.0.13 on 2019-10-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0044_auto_20191024_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcard',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
