# Generated by Django 2.0.13 on 2019-10-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0047_auto_20191025_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listcard',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='listcard',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
